"""Bridge to ``comet`` (the GOG Galaxy communication-service reimplementation).

Comet is a native Linux binary that provides the GOG Galaxy SDK communication
service so GOG games (running under Wine/Proton) can report achievements and
stats to GOG while played. Vitrine launches GOG games wrapped by a small script
that starts comet in the background and runs the game, then kills comet when the
game exits.

Comet needs the GOG access/refresh token, the user id and a username; the first
three come from Vitrine's :class:`GogTokenStore`, and the username is resolved
best-effort from ``users.gog.com`` (falling back to the user id).

Not all games need the ``GalaxyCommunication`` dummy Windows service, but some
do; :func:`register_dummy_service` registers it in the game's prefix (best
effort, requires the bundled ``GalaxyCommunication.exe``).
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from typing import Any

logger = logging.getLogger(__name__)

#: Environment override for the comet binary (mirrors VITRINE_LEGENDARY).
COMET_ENV = "VITRINE_COMET"

#: Setting key (bool): wrap GOG launches with comet for live achievement/stats.
COMET_ENABLED_SETTING = "gog_comet_enabled"

#: Comet's `-q` makes it quit shortly after its client disconnects.
_QUIT_FLAG = "-q"


class CometError(Exception):
    """Raised when comet is missing or unusable."""


def comet_binary() -> str:
    """Return the comet executable path, or raise if not installed."""
    override = os.environ.get(COMET_ENV)
    if override:
        return override
    path = shutil.which("comet")
    if not path:
        raise CometError(
            "comet is not installed. Install it (e.g. 'nixpkgs#comet-gog') or set "
            f"{COMET_ENV} to enable GOG achievements."
        )
    return path


def is_installed() -> bool:
    try:
        comet_binary()
        return True
    except CometError:
        return False


def comet_args(
    access_token: str,
    refresh_token: str,
    user_id: str,
    username: str,
) -> list[str]:
    """Argument vector for running comet as a background GOG service."""
    args = [
        comet_binary(),
        "--access-token",
        access_token,
        "--refresh-token",
        refresh_token,
        "--user-id",
        user_id,
        "--username",
        username,
        _QUIT_FLAG,
    ]
    return args


def resolve_username(user_id: str, access_token: str, timeout: int = 15) -> str | None:
    """Best-effort GOG username for ``user_id``, else ``None``.

    Reads ``https://users.gog.com/users/<id>`` with the provided Bearer token.
    Failure is non-fatal; callers fall back to the user id.
    """
    import requests

    url = f"https://users.gog.com/users/{user_id}"
    try:
        response = requests.get(url, headers={"Authorization": f"Bearer {access_token}"}, timeout=timeout)
        response.raise_for_status()
        data = response.json()
        return str(data.get("username") or "") or None
    except Exception:  # noqa: BLE001 - best effort
        logger.debug("Could not resolve GOG username for %s", user_id)
        return None


def write_wrapper(
    script_path: str,
    *,
    access_token: str,
    refresh_token: str,
    user_id: str,
    username: str,
) -> str:
    """Write a 0600 wrapper script that runs comet in the background then execs
    the game passed as ``"$@"``, killing comet when the game exits.

    The script embeds the tokens (hence a restrictive mode). Returns
    ``script_path`` for convenience.
    """
    args = comet_args(access_token, refresh_token, user_id, username)
    command_line = " ".join(shlex_quote(a) for a in args)
    os.makedirs(os.path.dirname(script_path), exist_ok=True)
    script = f"""#!/bin/sh
# Generated by Vitrine: run comet (GOG Galaxy communication service) alongside the game.
{command_line} &
COMET_PID=$!
trap 'kill $COMET_PID 2>/dev/null || true' EXIT INT TERM
exec "$@"
"""
    with open(script_path, "w", encoding="utf-8") as handle:
        handle.write(script)
    os.chmod(script_path, 0o600)
    return script_path


def shlex_quote(value: str) -> str:
    import shlex

    return shlex.quote(str(value))


def register_dummy_service(prefix: str, wine_binary: str, exe_path: str | None) -> None:
    """Register the GalaxyCommunication Windows service in ``prefix`` (best effort).

    Some GOG games expect the ``GalaxyCommunication.exe`` dummy service; without
    it they won't reach comet. ``prefix`` must exist. Errors are logged, never
    raised (a game must still be able to launch even if comet setup is partial).
    Tries ``sc create`` under wine.
    """
    if not prefix or not exe_path or not os.path.isfile(exe_path):
        return
    if not os.path.isdir(prefix):
        return
    windows_exe = "C:\\\\ProgramData\\\\GOG.com\\\\Galaxy\\\\redists\\\\GalaxyCommunication.exe"
    try:
        cmd = [wine_binary, "sc", "create", "GalaxyCommunication", "binPath=", windows_exe]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=_prefix_env(prefix))
        if result.returncode != 0:
            logger.warning("comet dummy service registration returned %s: %s", result.returncode, result.stderr.strip())
    except Exception:  # noqa: BLE001 - never block a launch
        logger.exception("comet dummy service registration failed")


def _prefix_env(prefix: str) -> dict[str, str]:
    env = dict(os.environ)
    env["WINEPREFIX"] = prefix
    return env


def read_tokens(library: Any) -> dict[str, str]:
    """Snapshot GOG tokens + ids for comet from the source's token store."""
    from vitrine.sources.gog_source import GogSource

    source = GogSource(library)
    if not source.is_authenticated():
        return {}
    store = source.login_token_store()
    access = store.access_token()
    if not access:
        return {}
    user_id = source.user_id
    username = resolve_username(str(user_id), access) or str(user_id)
    return {
        "access_token": access,
        "refresh_token": store.refresh_token(),
        "user_id": str(user_id),
        "username": username,
    }